### PR TITLE
Created notification state and page

### LINKED ISSUE #261: Create `NotificationState`
Like this:
```tsx
import { makeAutoObservable } from 'mobx';

type NotificationType = 'follow' | 'unfollow' | 'like' | 'unlike' | 'comment';

interface NotificationData {
  type: NotificationType;
  message?: string;
  createdAt: Date;
}

class NotificationState {
  private _type: NotificationType;
  private _message?: string;
  private _createdAt: Date;

  constructor(data: NotificationData) {
    this._type = data.type;
    this._message = data.message;
    this._createdAt = data.createdAt;
    makeAutoObservable(this);
  }

  get type(): NotificationType {
    return this._type;
  }

  set type(value: NotificationType) {
    this._type = value;
  }

  get message(): string | undefined {
    return this._message;
  }

  set message(value: string | undefined) {
    this._message = value;
  }

  get createdAt(): Date {
    return this._createdAt;
  }

  set createdAt(value: Date) {
    this._createdAt = value;
  }
}
```

### LINKED ISSUE #262: Create `pages/notification.tsx`
Above is example:
```tsx
import { ReactElement } from 'react';
import { NotificationState, NotificationData } from '../path/to/NotificationState';
import { NotificationList } from '../components/NotificationList';
import { PageTitle } from '../ui/PageTitle';
import { useObserver } from 'mobx-react-lite';

export default function NotificationPage(): ReactElement {
  const notifications = [
    new NotificationState({ type: 'follow', createdAt: new Date() }),
    new NotificationState({ type: 'like', message: 'Your post was liked!', createdAt: new Date() }),
    new NotificationState({ type: 'comment', message: 'You have a new comment!', createdAt: new Date() }),
  ];

  const notificationElements = notifications.map((notification) => (
    <NotificationList.Item key={notification.createdAt.toISOString()} notification={notification} />
  ));

  const handleAddNotification = (): void => {
    const data: NotificationData = {
      type: 'unfollow',
      createdAt: new Date(),
    };
    const notification = new NotificationState(data);
    notifications.push(notification);
  };

  return useObserver(() => (
    <NotificationState.Provider value={notifications}>
      <div className="flex flex-col gap-4">
        <PageTitle>Notifications</PageTitle>
        <NotificationList>{notificationElements}</NotificationList>
        <button className="px-4 py-2 text-white bg-blue-500 rounded" onClick={handleAddNotification}>
          Add Notification
        </button>
      </div>
    </NotificationState.Provider>
  ));
}
```

### PR DESCRIPTION
**Pull request by SharmaMitchell**
Closes #261 and closes #262
Implemented notification state, list component, and page. Also tweaked card styling and created stories file for notification list.

### CODE REVIEW

**Review by minamorl — CHANGES_REQUESTED** [review]
Can u make a page component stories as well?

**Comment by minamorl** [comment]
besides that lgtm

**Comment by SharmaMitchell** [comment]
> Can u make a page component stories as well?

Done! Will wait for review to merge 👍

**Review by minamorl — APPROVED** [review]
lgtm! ty

**Pull request merged**
