### PR TITLE
Wrap classes that uses MobX with hooks

### PR DESCRIPTION
**Pull request by keito-jp**
Wrap classes that uses MobX with hooks.

In addition, models that did not need to be classed were eliminated.

### CODE REVIEW

**Review by minamorl — CHANGES_REQUESTED** [review]
CommentInput component is invisible on storybook

**Comment by minamorl** [comment]
@keito-jp Basically LGTM. But i would like to let u make some comments so that the other devs can easily read?

**Comment by minamorl** [comment]
But if it takes time pls proceed next tasks

**Comment by keito-jp** [comment]
@minamorl I fixed it!

**Pull request merged**
