### PR TITLE
Implemented card components

### PR DESCRIPTION
**Pull request by SharmaMitchell**
- AttachedImages
  - Copied styling from v1 card/post styles, as a placeholder (See ui\common\CardContent.tsx)
- ReactionButtons
  - Placeholder onClick function & icons (used emoji)

### CODE REVIEW

**Comment by minamorl** [comment]
lol i didnt know that spec

**Review by minamorl — APPROVED** [review]
🎉

**Comment by minamorl** [comment]
can u fix the problem?

**Comment by SharmaMitchell** [comment]
> can u fix the problem?

What problem, The vercel deployment? Idk what checks are failing, don't have access to vercel

**Comment by minamorl** [comment]
```
./ui/v2/features/Post/Reply.tsx:15:9
--
17:59:16.014 | Type error: All destructured elements are unused.
17:59:16.014 |  
17:59:16.015 | 13 \|
17:59:16.015 | 14 \| export default function Reply(props: Props) {
17:59:16.015 | > 15 \|   const { authorUserId, authorScreenName, body, likesCount, repliesCount, createdAt, userIcon } =
17:59:16.015 | \|         ^
17:59:16.015 | 16 \|     props
```
So problem is destructuring.

**Comment by SharmaMitchell** [comment]
Ahh ok, that's gutchom's placeholder code for the new components. Should be ok since we're still working on it - just trying to merge into gutchom's branch so he can style & tweak my implementations.

**Comment by minamorl** [comment]
@SharmaMitchell It's only frontend so feel free to merge at your timing. leave it to you

**Comment by SharmaMitchell** [comment]
Okey dokey, will wait for @gutchom to review

**Review by gutchom — APPROVED** [review]
LGTM!

**Pull request merged**
